# Generated by Django 5.1.15 on 2026-06-07 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Paket Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Ücret (TL)')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yıllık Ücret (TL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Abonelik Paketi',
                'verbose_name_plural': 'Abonelik Paketleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firma Adı')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Şehir')),
                ('subscription_status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('suspended', 'Askıya Alınmış'), ('trial', 'Deneme')], default='trial', max_length=20, verbose_name='Abonelik Durumu')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='Abonelik Başlangıç')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Abonelik Bitiş')),
                ('package_name', models.CharField(blank=True, max_length=120, verbose_name='Paket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
