# Generated by Django 5.1.15 on 2026-06-07 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Anahtar Kelime')),
                ('category', models.CharField(blank=True, choices=[('yapim_ihaleleri', 'Yapım İhaleleri'), ('mal_alimi', 'Mal Alımı İhaleleri'), ('hizmet_alimi', 'Hizmet Alımı İhaleleri'), ('danismanlik', 'Danışmanlık İhaleleri'), ('duzeltme_ilanlari', 'Düzeltme İlanları'), ('iptal_ilanlari', 'İptal İlanları'), ('ihale_sonuclari', 'İhale Sonuçları'), ('kesinlesen_sonuclar', 'Kesinleşen Sonuçlar'), ('dogrudan_temin', 'Doğrudan Temin'), ('elektrik_mekanik', 'Elektrik ve Mekanik İşler'), ('insaat_altyapi', 'İnşaat ve Altyapı'), ('arac_makine', 'Araç ve Makine'), ('gida', 'Gıda'), ('temizlik', 'Temizlik'), ('guvenlik', 'Güvenlik'), ('saglik', 'Sağlık'), ('yazilim_otomasyon', 'Yazılım ve Otomasyon'), ('egitim', 'Eğitim'), ('belediye_hizmetleri', 'Belediye Hizmetleri'), ('ulasim', 'Ulaşım'), ('enerji', 'Enerji'), ('diger', 'Diğer')], max_length=40, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Anahtar Kelime',
                'verbose_name_plural': 'Anahtar Kelimeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='İl Adı')),
                ('plate_code', models.PositiveSmallIntegerField(unique=True, verbose_name='Plaka Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['plate_code'],
            },
        ),
        migrations.CreateModel(
            name='TenderFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('partial', 'Kısmen Başarılı'), ('failed', 'Başarısız'), ('running', 'Çalışıyor')], default='running', max_length=20, verbose_name='Durum')),
                ('source', models.CharField(blank=True, max_length=20, verbose_name='Kaynak')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='İlçe')),
                ('total_found', models.PositiveIntegerField(default=0, verbose_name='Bulunan Kayıt')),
                ('new_records', models.PositiveIntegerField(default=0, verbose_name='Yeni Kayıt')),
                ('duplicate_records', models.PositiveIntegerField(default=0, verbose_name='Tekrar Eden')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
            ],
            options={
                'verbose_name': 'İhale Çekme Logu',
                'verbose_name_plural': 'İhale Çekme Logları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_no', models.CharField(db_index=True, max_length=60, verbose_name='İhale Kayıt No')),
                ('title', models.CharField(max_length=500, verbose_name='İhale Başlığı')),
                ('authority_name', models.CharField(blank=True, max_length=300, verbose_name='İdare Adı')),
                ('province', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='İl')),
                ('district', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='İlçe')),
                ('tender_type', models.CharField(blank=True, choices=[('YAPIM', 'Yapım'), ('MAL', 'Mal Alımı'), ('HIZMET', 'Hizmet Alımı'), ('DANISMANLIK', 'Danışmanlık')], max_length=20, verbose_name='İhale Türü')),
                ('category', models.CharField(blank=True, choices=[('yapim_ihaleleri', 'Yapım İhaleleri'), ('mal_alimi', 'Mal Alımı İhaleleri'), ('hizmet_alimi', 'Hizmet Alımı İhaleleri'), ('danismanlik', 'Danışmanlık İhaleleri'), ('duzeltme_ilanlari', 'Düzeltme İlanları'), ('iptal_ilanlari', 'İptal İlanları'), ('ihale_sonuclari', 'İhale Sonuçları'), ('kesinlesen_sonuclar', 'Kesinleşen Sonuçlar'), ('dogrudan_temin', 'Doğrudan Temin'), ('elektrik_mekanik', 'Elektrik ve Mekanik İşler'), ('insaat_altyapi', 'İnşaat ve Altyapı'), ('arac_makine', 'Araç ve Makine'), ('gida', 'Gıda'), ('temizlik', 'Temizlik'), ('guvenlik', 'Güvenlik'), ('saglik', 'Sağlık'), ('yazilim_otomasyon', 'Yazılım ve Otomasyon'), ('egitim', 'Eğitim'), ('belediye_hizmetleri', 'Belediye Hizmetleri'), ('ulasim', 'Ulaşım'), ('enerji', 'Enerji'), ('diger', 'Diğer')], db_index=True, max_length=40, verbose_name='Kategori')),
                ('tender_procedure', models.CharField(blank=True, choices=[('acik', 'Açık İhale Usulü'), ('belli_istekliler', 'Belli İstekliler Arasında İhale'), ('pazarlik', 'Pazarlık Usulü'), ('dogrudan_temin', 'Doğrudan Temin'), ('diger', 'Diğer')], max_length=40, verbose_name='İhale Usulü')),
                ('announcement_date', models.DateField(blank=True, null=True, verbose_name='İlan Tarihi')),
                ('tender_date', models.DateField(blank=True, null=True, verbose_name='İhale Tarihi')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Son Teklif Tarihi')),
                ('work_location', models.CharField(blank=True, max_length=300, verbose_name='İşin Yapılacağı Yer')),
                ('short_description', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('official_url', models.URLField(blank=True, max_length=500, verbose_name='Resmî / EKAP Link')),
                ('source', models.CharField(choices=[('EKAP', 'EKAP (Elektronik Kamu Alımları Platformu)'), ('RESMI_GAZETE', 'Resmî Gazete'), ('MOCK', 'Örnek / Demo Veri')], default='MOCK', max_length=20, verbose_name='Kaynak')),
                ('status', models.CharField(choices=[('aktif', 'Aktif / Açık'), ('sonuclandi', 'Sonuçlandı'), ('kesinlesti', 'Kesinleşti'), ('iptal', 'İptal'), ('duzeltme', 'Düzeltme')], default='aktif', max_length=20, verbose_name='Durum')),
                ('keyword_matches', models.CharField(blank=True, max_length=300, verbose_name='Anahtar Kelime Eşleşmesi')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sisteme Eklenme')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'İhale',
                'verbose_name_plural': 'İhaleler',
                'ordering': ['-announcement_date', '-created_at'],
                'indexes': [models.Index(fields=['province', 'category'], name='tenders_ten_provinc_4b26bb_idx'), models.Index(fields=['announcement_date'], name='tenders_ten_announc_99e172_idx')],
                'constraints': [models.UniqueConstraint(fields=('tender_no', 'source'), name='uniq_tender_no_source')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='İşlem')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivite Logu',
                'verbose_name_plural': 'Kullanıcı Aktivite Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='İlçe Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='tenders.province', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['province__plate_code', 'name'],
                'unique_together': {('province', 'name')},
            },
        ),
    ]
