# Generated by Django 5.1.15 on 2026-06-07 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tender',
            name='tenders_ten_provinc_4b26bb_idx',
        ),
        migrations.AddField(
            model_name='tender',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='İlk Görülme'),
        ),
        migrations.AddField(
            model_name='tender',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Son Görülme'),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('YAPIM', 'Yapım'), ('MAL', 'Mal Alımı'), ('HIZMET', 'Hizmet Alımı'), ('DANISMANLIK', 'Danışmanlık')], db_index=True, max_length=20, verbose_name='Alım Türü'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='announcement_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='İlan Tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sisteme Eklenme'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Son Teklif Tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif / Açık'), ('sonuclandi', 'Sonuçlandı'), ('kesinlesti', 'Kesinleşti'), ('iptal', 'İptal'), ('duzeltme', 'Düzeltme')], db_index=True, default='aktif', max_length=40, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='İhale Tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_procedure',
            field=models.CharField(blank=True, max_length=100, verbose_name='İhale Usulü'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='İhale Türü'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='work_location',
            field=models.CharField(blank=True, max_length=500, verbose_name='İşin Yapılacağı Yer'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['tender_no'], name='tenders_ten_tender__997b52_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['province'], name='tenders_ten_provinc_34eed1_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['district'], name='tenders_ten_distric_19a8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['procurement_type'], name='tenders_ten_procure_59857a_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['tender_date'], name='tenders_ten_tender__8e66ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['deadline_date'], name='tenders_ten_deadlin_17d548_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status'], name='tenders_ten_status_955cba_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['created_at'], name='tenders_ten_created_c30c2e_idx'),
        ),
    ]
